### ISSUE TITLE
Doesn't pull other linked libraries

### ISSUE THREAD

**Issue by abinashmohanty** [perrysmotors/sketch-library-unlinker#2]
Some how this plugin **doesn't fetch** all my linked sketch libraries. check attached image where it doesn't pull other libraries. 

<img width="420" alt="screen shot 2018-05-17 at 4 48 38 pm" src="https://user-images.githubusercontent.com/8434934/40175021-769ceede-59f4-11e8-90e2-25d6cf5a8937.png">

**Comment by perrysmotors** [comment]
@abinashmohanty Never got a notification from Github about this issue. Very sorry.

The plugin is designed to only list libraries in cases where symbols from the library are actually used in in the document. i.e. If you don't see a library in the dropdown it should mean that no symbols from that library have been used in the document. If you can see symbols from a library and the library still doesn't appear in the dropdown let me know.
