### ISSUE TITLE
Plugin doesn't unlink library

### ISSUE THREAD

**Issue by alolalo** [perrysmotors/sketch-library-unlinker#5]
Hi Perry!

Thanks for making this, I've been using it for a long while. It stopped working for me, and this is the workflow I'm used to;

- Create a new file, and import the symbols from another library
- Draw in the symbols from a shared library with Symbol Instance Sheet
- Use library unlinker to turn them into local symbols

This used to work flawlessly, yet the result is that your plugin does run the script without errors, only it doesn't do what it supposed to anymore; unlink the symbols from the library.

They stay connected to the shared library (symbol icon remains a chain) and the generated page does not include any symbols that were converted form a shared library to a local one.

Hope this helps and feel free to ask for clarifications!

Greetings,
Guus

**Comment by alolalo** [comment]
For your information; I use cloud libraries (used to work before) and of creating a symbol instance sheet from a remote source. Given Sketch's API update I believe it's fixable since the plugin doesn't throw any errors, just doesn't find anything because the syntax changed. Hope this helps!

**Comment by nlourenco** [comment]
Reporting the same, however my workflow is slightly different from OP:

1. Create file
2. Drop in symbols from a shared library
3. Use library unlinker to turn into local symbols

- Sketch Version 58 (84663)
- macOS 10.14.6 (18G95)
- Symbol Instance

**Comment by alexkaessner** [comment]
I just downloaded the plugin and tested it with **Sketch Version 61.2** (macOS 10.15.2). The plugin is still not working correctly for me.

It detects that I used an external library, but once I let the plugin do it's work it only creates an empty new page. All the symbols stay connected to its library.

**Comment by perrysmotors** [comment]
@alexkaessner I think I've fixed it. Can you check and let me know.

**Comment by alexkaessner** [comment]
@perrysmotors Yes, it now works fine for me! 👍

Btw, would be nice to have the auto update feature enabled for this plugin.

**Comment by perrysmotors** [comment]
@alexkaessner Are you saying that you are not getting a Plugin Update notification in Sketch? I've created an .appcast.xml file so you should get notified and you should be able to update the plugin within Sketch. It's possible the notification only shows up when you restart Sketch or there is a delay.

**Comment by perrysmotors** [comment]
@alolalo and @nlourenco Very sorry I didn't get notified by Github about the plugin not working. I need to fix my notification settings. Anyway the plugin should be fixed now.
